#!/usr/bin/python3
#
#makeblastdb -in () -title () -dbtype prot #make db directory because this outputs 3 files
# clustalo -i () -o ()
#blastp -db () -query ()
#cons -sequence () -outseq ()
#subprocess.Popen(['clustalo', '-i', f"{taxonomy}.fa", '-o', f"{taxonomy}.clstl"]) 
import sys
import subprocess
import os
import xml.etree.ElementTree as ET
import re



#
aves = open('/localdisk/home/s1992281/Assignment2/aves.fa', 'r')
outputs = []
for seq in aves.readlines() :
 if re.search('[.+]', seq) :
  outputs.append(seq)
print(list(outputs))
  
